---
title: "Cell Type Comparison"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}
library(ggplot2)
library(scales)
```

```{r}
Idents(xen1diet) <- "cell_type"

idents <- as.character(Idents(xen1diet))

xen1diet$broad_type <- case_when(
  grepl("^PTS", idents) ~ "PT",
  grepl("^TAL", idents) ~ "TAL",
  grepl("^ATL|^DTL", idents) ~ "Thin limb",
  grepl("^CD", idents) ~ "Collecting duct",
  grepl("^DCT", idents) ~ "DCT",
  grepl("^STROMA", idents) ~ "Stroma",
  grepl("^ENDO", idents) ~ "Endothelium",
  grepl("^GEnC", idents) ~ "Endothelium",
  grepl("^VSMC", idents) ~ "Vascular",
  grepl("^IMMUNE", idents) ~ "Immune",
  grepl("^MESANGIAL", idents) ~ "Glomerular",
  grepl("^PODO", idents) ~ "Glomerular",
  grepl("^PEC", idents) ~ "Glomerular",
  grepl("^UROTHELIUM", idents) ~ "Urothelium",
  grepl("^FAT", idents) ~ "Adipose",
  grepl("^rare", idents) ~ "Rare",
  TRUE ~ "Other"
)
```

```{r}
xen1diet$time_point <- factor(
  xen1diet$time_point,
  levels = c("1wk", "2wk", "4wk", "12wk")
)

plot_data <- subset(
  xen1diet@meta.data,
  !is.na(time_point)
)

p_celltypeComposition <- ggplot(
  plot_data,
  aes(time_point, fill = broad_type)
) +
  
  geom_bar(position = "fill") +
  scale_y_continuous(
    labels = percent_format()
  ) +
  
  labs(
    x = "Developmental stage",
    y = "Cell Proportion",
    fill = "Broad cell type",
    title = "Cell Type Composition",
    subtitle = settings$dataset
  )

ggsave(
  filename = file.path(
    "results",
    "figures",
    paste0(
      name, "_",
      settings$dataset, "_",
      settings$region,
      sex_label,
      "_celltypeComposition.png"
    )
  ),
  
  plot = p_celltypeComposition,
  width = 6,
  height = 5,
)

```